AllCops:
  Exclude:
    - test/**/*
    - Gemfile
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120

Metrics/ParameterLists:
  Max: 8

Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
